"""initial migration

Revision ID: 2d1d2ad34fe7
Revises: 
Create Date: 2021-03-04 02:25:25.264220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d1d2ad34fe7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('firstname', sa.String(), nullable=False),
    sa.Column('lastname', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cust_name', sa.String(length=30), nullable=False),
    sa.Column('contact_num', sa.String(), nullable=False),
    sa.Column('job_requested', sa.String(), nullable=False),
    sa.Column('job_created', sa.DateTime(), nullable=False),
    sa.Column('job_date', sa.Date(), nullable=False),
    sa.Column('job_time', sa.Time(), nullable=True),
    sa.Column('job_address', sa.String(length=100), nullable=False),
    sa.Column('job_status', sa.String(), nullable=False),
    sa.Column('job_notes', sa.String(length=120), nullable=True),
    sa.Column('job_type_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_type_id'], ['job_types.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobs')
    op.drop_table('profiles')
    op.drop_table('users')
    op.drop_table('job_types')
    # ### end Alembic commands ###
