name: CI/CD
on:
  push:
    branches: [master]

jobs:
  test_suite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
      - name: Set Up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run Tests
        env:
          FLASK_ENV: testing
        run: |
          cd src
          python -m unittest discover -s tests/ -v
  # deployment:
  #   needs: test_suite
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Fresh clone & repo install
  #       uses: appleboy/ssh-action@master
  #       with:
  #         host: 34.228.96.189
  #         username: github-actions
  #         key: ${{ secrets.SHH_KEY }}
  #         port: 22
  #         script: |
  #           rm -rf Cleaning-and-Laundry-Management-System
  #           git clone https://github.com/hholly3003/Cleaning-and-Laundry-Management-System.git
  #           python3.8 -m venv /home/github-actions/Cleaning-and-Laundry-Management-System/venv
  #           /home/github-actions/Cleaning-and-Laundry-Management-System/venv/bin/pip3.8 install -r /home/github-actions/Cleaning-and-Laundry-Management-System/requirements.txt